/*
 * This file is part of BedrockProtocol for Endstone.
 * C++ port of the PHP original: src/PacketPool.php
 * Copyright (C) 2014-2022 PocketMine Team <https://github.com/pmmp/BedrockProtocol>
 *
 * BedrockProtocol is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

#include "bedrock_protocol/protocol/PacketPool.h"

#include "bedrock_protocol/encoding/ByteBufferReader.h"
#include "bedrock_protocol/encoding/DataDecodeException.h"
#include "bedrock_protocol/encoding/VarInt.h"
#include "bedrock_protocol/protocol/AllPackets.h"

namespace bedrock_protocol {

PacketPool::PacketPool()
{
// This registration list is generated by tools/gen_from_php.py; do not edit it manually.
#include "bedrock_protocol/protocol/PacketPool.registrations.inc"
}

const PacketPool &PacketPool::getInstance()
{
    static const PacketPool instance;
    return instance;
}

std::unique_ptr<DataPacket> PacketPool::getPacketById(std::uint32_t pid) const
{
    if (pid >= POOL_SIZE || pool_[pid] == nullptr) {
        return nullptr;
    }
    return pool_[pid]();
}

std::unique_ptr<DataPacket> PacketPool::getPacket(std::string_view buffer) const
{
    encoding::ByteBufferReader in(buffer);
    try {
        return getPacketById(encoding::VarInt::readUnsignedInt(in) & DataPacket::PID_MASK);
    }
    catch (const encoding::DataDecodeException &) {
        return nullptr;
    }
}

}  // namespace bedrock_protocol
