/*
 * This file is part of BedrockProtocol-Cpp.
 *
 * Puts the port's base64 decoder side by side with PHP's own, on every input in
 * Base64Fixtures.inc - which tools/gen_base64_fixtures.php generated by asking PHP what
 * base64_decode($s, true) returns for each one.
 *
 * This decoder is the one hand-written parser the packet suites cannot reach: it runs on the login
 * JWT payload rather than on the wire, so a padding or truncation mistake in it would surface as
 * real clients failing to log in, with nothing in the test output to point at it. Accepting an input
 * PHP rejects matters as much as the reverse, because both sides feed a skin straight from what
 * comes back.
 */

#include <optional>
#include <string>
#include <string_view>

#include "TestHarness.h"
#include "bedrock_protocol/protocol/types/login/clientdata/ClientDataToSkinDataHelper.h"

using bedrock_protocol::types::login::clientdata::detail::strictBase64Decode;

namespace {

struct Case {
    std::string_view input;
    bool accepted;
    std::string_view decoded;
};

// Both views are built with an explicit length: decoded output contains NUL bytes, and a view
// constructed from the literal alone would stop at the first one and silently compare equal.
constexpr Case CASES[] = {
#define BP_BASE64_CASE(input, inputLen, accepted, decoded, decodedLen) \
    {std::string_view(input, inputLen), accepted, std::string_view(decoded, decodedLen)},
#include "Base64Fixtures.inc"
#undef BP_BASE64_CASE
};

}  // namespace

int main()
{
    int acceptedByPhp = 0;
    int rejectedByPhp = 0;
    int wronglyAccepted = 0;
    int wronglyRejected = 0;
    int wrongOutput = 0;

    for (const auto &expected : CASES) {
        (expected.accepted ? acceptedByPhp : rejectedByPhp)++;

        const auto actual = strictBase64Decode(expected.input);
        if (actual.has_value() != expected.accepted) {
            (expected.accepted ? wronglyRejected : wronglyAccepted)++;
            if (wronglyAccepted + wronglyRejected <= 10) {
                std::fprintf(stderr, "  %-24s php %s, port %s\n",
                             bedrock_protocol::test::toHex(expected.input).c_str(),
                             expected.accepted ? "accepted" : "rejected",
                             actual.has_value() ? "accepted" : "rejected");
            }
            continue;
        }
        if (actual.has_value() && *actual != expected.decoded) {
            ++wrongOutput;
            if (wrongOutput <= 10) {
                std::fprintf(stderr, "  %-24s php %s, port %s\n",
                             bedrock_protocol::test::toHex(expected.input).c_str(),
                             bedrock_protocol::test::toHex(expected.decoded).c_str(),
                             bedrock_protocol::test::toHex(*actual).c_str());
            }
        }
    }

    std::printf("base64 decoder against PHP's base64_decode($s, true)\n");
    std::printf("  inputs               %zu\n", std::size(CASES));
    std::printf("    accepted by PHP    %d\n", acceptedByPhp);
    std::printf("    rejected by PHP    %d\n", rejectedByPhp);

    CHECK_EQ(wronglyAccepted, 0);
    CHECK_EQ(wronglyRejected, 0);
    CHECK_EQ(wrongOutput, 0);
    return bedrock_protocol::test::summarise("Base64ParityTest");
}
