/*
 * This file is part of BedrockProtocol-Cpp.
 * C++ port of the PHP original: src/types/entity/EntityIds.php
 * Copyright (C) 2014-2022 PocketMine Team <https://github.com/pmmp/BedrockProtocol>
 *
 * BedrockProtocol is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

#pragma once

#include <string_view>

namespace bedrock_protocol::types::entity {

/**
 * This file is automatically generated; do NOT edit it by hand.
 * Regenerate it by running tools/generate-entity-ids.php
 */
class EntityIds final {
    EntityIds() = delete;

public:
    static constexpr std::string_view AGENT = "minecraft:agent";
    static constexpr std::string_view ALLAY = "minecraft:allay";
    static constexpr std::string_view AREA_EFFECT_CLOUD = "minecraft:area_effect_cloud";
    static constexpr std::string_view ARMADILLO = "minecraft:armadillo";
    static constexpr std::string_view ARMOR_STAND = "minecraft:armor_stand";
    static constexpr std::string_view ARROW = "minecraft:arrow";
    static constexpr std::string_view AXOLOTL = "minecraft:axolotl";
    static constexpr std::string_view BALLOON = "minecraft:balloon";
    static constexpr std::string_view BAT = "minecraft:bat";
    static constexpr std::string_view BEE = "minecraft:bee";
    static constexpr std::string_view BLAZE = "minecraft:blaze";
    static constexpr std::string_view BOAT = "minecraft:boat";
    static constexpr std::string_view BOGGED = "minecraft:bogged";
    static constexpr std::string_view BREEZE = "minecraft:breeze";
    static constexpr std::string_view BREEZE_WIND_CHARGE_PROJECTILE = "minecraft:breeze_wind_charge_projectile";
    static constexpr std::string_view CAMEL = "minecraft:camel";
    static constexpr std::string_view CAMEL_HUSK = "minecraft:camel_husk";
    static constexpr std::string_view CAT = "minecraft:cat";
    static constexpr std::string_view CAVE_SPIDER = "minecraft:cave_spider";
    static constexpr std::string_view CHEST_BOAT = "minecraft:chest_boat";
    static constexpr std::string_view CHEST_MINECART = "minecraft:chest_minecart";
    static constexpr std::string_view CHICKEN = "minecraft:chicken";
    static constexpr std::string_view COD = "minecraft:cod";
    static constexpr std::string_view COMMAND_BLOCK_MINECART = "minecraft:command_block_minecart";
    static constexpr std::string_view COPPER_GOLEM = "minecraft:copper_golem";
    static constexpr std::string_view COW = "minecraft:cow";
    static constexpr std::string_view CREAKING = "minecraft:creaking";
    static constexpr std::string_view CREEPER = "minecraft:creeper";
    static constexpr std::string_view DOLPHIN = "minecraft:dolphin";
    static constexpr std::string_view DONKEY = "minecraft:donkey";
    static constexpr std::string_view DRAGON_FIREBALL = "minecraft:dragon_fireball";
    static constexpr std::string_view DROWNED = "minecraft:drowned";
    static constexpr std::string_view EGG = "minecraft:egg";
    static constexpr std::string_view ELDER_GUARDIAN = "minecraft:elder_guardian";
    static constexpr std::string_view ELDER_GUARDIAN_GHOST = "minecraft:elder_guardian_ghost";
    static constexpr std::string_view ENDER_CRYSTAL = "minecraft:ender_crystal";
    static constexpr std::string_view ENDER_DRAGON = "minecraft:ender_dragon";
    static constexpr std::string_view ENDER_PEARL = "minecraft:ender_pearl";
    static constexpr std::string_view ENDERMAN = "minecraft:enderman";
    static constexpr std::string_view ENDERMITE = "minecraft:endermite";
    static constexpr std::string_view EVOCATION_FANG = "minecraft:evocation_fang";
    static constexpr std::string_view EVOCATION_ILLAGER = "minecraft:evocation_illager";
    static constexpr std::string_view EYE_OF_ENDER_SIGNAL = "minecraft:eye_of_ender_signal";
    static constexpr std::string_view FALLING_BLOCK = "minecraft:falling_block";
    static constexpr std::string_view FIREBALL = "minecraft:fireball";
    static constexpr std::string_view FIREWORKS_ROCKET = "minecraft:fireworks_rocket";
    static constexpr std::string_view FISHING_HOOK = "minecraft:fishing_hook";
    static constexpr std::string_view FOX = "minecraft:fox";
    static constexpr std::string_view FROG = "minecraft:frog";
    static constexpr std::string_view GHAST = "minecraft:ghast";
    static constexpr std::string_view GLOW_SQUID = "minecraft:glow_squid";
    static constexpr std::string_view GOAT = "minecraft:goat";
    static constexpr std::string_view GUARDIAN = "minecraft:guardian";
    static constexpr std::string_view HAPPY_GHAST = "minecraft:happy_ghast";
    static constexpr std::string_view HOGLIN = "minecraft:hoglin";
    static constexpr std::string_view HOPPER_MINECART = "minecraft:hopper_minecart";
    static constexpr std::string_view HORSE = "minecraft:horse";
    static constexpr std::string_view HUSK = "minecraft:husk";
    static constexpr std::string_view ICE_BOMB = "minecraft:ice_bomb";
    static constexpr std::string_view IRON_GOLEM = "minecraft:iron_golem";
    static constexpr std::string_view ITEM = "minecraft:item";
    static constexpr std::string_view LEASH_KNOT = "minecraft:leash_knot";
    static constexpr std::string_view LIGHTNING_BOLT = "minecraft:lightning_bolt";
    static constexpr std::string_view LINGERING_POTION = "minecraft:lingering_potion";
    static constexpr std::string_view LLAMA = "minecraft:llama";
    static constexpr std::string_view LLAMA_SPIT = "minecraft:llama_spit";
    static constexpr std::string_view MAGMA_CUBE = "minecraft:magma_cube";
    static constexpr std::string_view MINECART = "minecraft:minecart";
    static constexpr std::string_view MOOSHROOM = "minecraft:mooshroom";
    static constexpr std::string_view MULE = "minecraft:mule";
    static constexpr std::string_view NAUTILUS = "minecraft:nautilus";
    static constexpr std::string_view NPC = "minecraft:npc";
    static constexpr std::string_view OCELOT = "minecraft:ocelot";
    static constexpr std::string_view OMINOUS_ITEM_SPAWNER = "minecraft:ominous_item_spawner";
    static constexpr std::string_view PAINTING = "minecraft:painting";
    static constexpr std::string_view PANDA = "minecraft:panda";
    static constexpr std::string_view PARCHED = "minecraft:parched";
    static constexpr std::string_view PARROT = "minecraft:parrot";
    static constexpr std::string_view PHANTOM = "minecraft:phantom";
    static constexpr std::string_view PIG = "minecraft:pig";
    static constexpr std::string_view PIGLIN = "minecraft:piglin";
    static constexpr std::string_view PIGLIN_BRUTE = "minecraft:piglin_brute";
    static constexpr std::string_view PILLAGER = "minecraft:pillager";
    static constexpr std::string_view PLAYER = "minecraft:player";
    static constexpr std::string_view POLAR_BEAR = "minecraft:polar_bear";
    static constexpr std::string_view PUFFERFISH = "minecraft:pufferfish";
    static constexpr std::string_view RABBIT = "minecraft:rabbit";
    static constexpr std::string_view RAVAGER = "minecraft:ravager";
    static constexpr std::string_view SALMON = "minecraft:salmon";
    static constexpr std::string_view SHEEP = "minecraft:sheep";
    static constexpr std::string_view SHULKER = "minecraft:shulker";
    static constexpr std::string_view SHULKER_BULLET = "minecraft:shulker_bullet";
    static constexpr std::string_view SILVERFISH = "minecraft:silverfish";
    static constexpr std::string_view SKELETON = "minecraft:skeleton";
    static constexpr std::string_view SKELETON_HORSE = "minecraft:skeleton_horse";
    static constexpr std::string_view SLIME = "minecraft:slime";
    static constexpr std::string_view SMALL_FIREBALL = "minecraft:small_fireball";
    static constexpr std::string_view SNIFFER = "minecraft:sniffer";
    static constexpr std::string_view SNOW_GOLEM = "minecraft:snow_golem";
    static constexpr std::string_view SNOWBALL = "minecraft:snowball";
    static constexpr std::string_view SPIDER = "minecraft:spider";
    static constexpr std::string_view SPLASH_POTION = "minecraft:splash_potion";
    static constexpr std::string_view SQUID = "minecraft:squid";
    static constexpr std::string_view STRAY = "minecraft:stray";
    static constexpr std::string_view STRIDER = "minecraft:strider";
    static constexpr std::string_view SULFUR_CUBE = "minecraft:sulfur_cube";
    static constexpr std::string_view TADPOLE = "minecraft:tadpole";
    static constexpr std::string_view THROWN_TRIDENT = "minecraft:thrown_trident";
    static constexpr std::string_view TNT = "minecraft:tnt";
    static constexpr std::string_view TNT_MINECART = "minecraft:tnt_minecart";
    static constexpr std::string_view TRADER_LLAMA = "minecraft:trader_llama";
    static constexpr std::string_view TRIPOD_CAMERA = "minecraft:tripod_camera";
    static constexpr std::string_view TROPICALFISH = "minecraft:tropicalfish";
    static constexpr std::string_view TURTLE = "minecraft:turtle";
    static constexpr std::string_view VEX = "minecraft:vex";
    static constexpr std::string_view VILLAGER = "minecraft:villager";
    static constexpr std::string_view VILLAGER_V2 = "minecraft:villager_v2";
    static constexpr std::string_view VINDICATOR = "minecraft:vindicator";
    static constexpr std::string_view WANDERING_TRADER = "minecraft:wandering_trader";
    static constexpr std::string_view WARDEN = "minecraft:warden";
    static constexpr std::string_view WIND_CHARGE_PROJECTILE = "minecraft:wind_charge_projectile";
    static constexpr std::string_view WITCH = "minecraft:witch";
    static constexpr std::string_view WITHER = "minecraft:wither";
    static constexpr std::string_view WITHER_SKELETON = "minecraft:wither_skeleton";
    static constexpr std::string_view WITHER_SKULL = "minecraft:wither_skull";
    static constexpr std::string_view WITHER_SKULL_DANGEROUS = "minecraft:wither_skull_dangerous";
    static constexpr std::string_view WOLF = "minecraft:wolf";
    static constexpr std::string_view XP_BOTTLE = "minecraft:xp_bottle";
    static constexpr std::string_view XP_ORB = "minecraft:xp_orb";
    static constexpr std::string_view ZOGLIN = "minecraft:zoglin";
    static constexpr std::string_view ZOMBIE = "minecraft:zombie";
    static constexpr std::string_view ZOMBIE_HORSE = "minecraft:zombie_horse";
    static constexpr std::string_view ZOMBIE_NAUTILUS = "minecraft:zombie_nautilus";
    static constexpr std::string_view ZOMBIE_PIGMAN = "minecraft:zombie_pigman";
    static constexpr std::string_view ZOMBIE_VILLAGER = "minecraft:zombie_villager";
    static constexpr std::string_view ZOMBIE_VILLAGER_V2 = "minecraft:zombie_villager_v2";
};

}  // namespace bedrock_protocol::types::entity
