<?php

/**
 * Generates encoding test vectors from the reference PHP implementation.
 *
 * The protocol's primitives are normally provided by the ext-encoding C extension, which is not
 * installed here; pocketmine/binaryutils implements the identical set in plain PHP and is the
 * reference the extension itself was written against, so it is used as the oracle.
 *
 * Output: tests/fixtures/encoding.inc - a C++ table included by tests/EncodingTest.cpp.
 *
 * Usage: php tools/gen_fixtures.php
 */

declare(strict_types=1);

require 'c:/Users/User/Desktop/BetterPMMP/source/vendor/pocketmine/binaryutils/src/BinaryDataException.php';
require 'c:/Users/User/Desktop/BetterPMMP/source/vendor/pocketmine/binaryutils/src/Binary.php';

use pocketmine\utils\Binary;

/** Values chosen to exercise sign boundaries, zigzag behaviour and the multi-byte length steps. */
const UNSIGNED_INT_CASES = [0, 1, 127, 128, 255, 300, 16383, 16384, 2097151, 2097152, 268435455, 268435456, 4294967295];
const SIGNED_INT_CASES = [0, -1, 1, -2, 2, 63, -64, 64, -65, 2147483647, -2147483648, 12345, -12345];
const UNSIGNED_LONG_CASES = [0, 1, 127, 128, 4294967296, 72057594037927936, 9223372036854775807];
const SIGNED_LONG_CASES = [0, -1, 1, -2, 4294967296, -4294967296, 9223372036854775807, PHP_INT_MIN];

function cppBytes(string $raw): string
{
    $parts = [];
    for ($i = 0, $n = strlen($raw); $i < $n; ++$i) {
        $parts[] = sprintf('\\x%02x', ord($raw[$i]));
    }
    return '"' . implode('', $parts) . '"';
}

$lines = [];
$lines[] = '// Generated by tools/gen_fixtures.php from pocketmine/binaryutils. Do not edit.';
$lines[] = '// Each entry is {value, expected encoded bytes, byte count}.';
$lines[] = '';

$emit = static function (string $name, string $cppType, array $cases, callable $encode) use (&$lines): void {
    $lines[] = "const std::vector<std::tuple<{$cppType}, std::string_view>> {$name} = {";
    foreach ($cases as $value) {
        $raw = $encode($value);
        // An explicit cast keeps the literal's own type (which the compiler widens for values that do
        // not fit an int) from narrowing inside the tuple's braced initialiser.
        $literal = $value === PHP_INT_MIN ? 'INT64_MIN' : (string)$value;
        $lines[] = sprintf('    {static_cast<%s>(%s), std::string_view(%s, %d)},', $cppType, $literal, cppBytes($raw), strlen($raw));
    }
    $lines[] = '};';
    $lines[] = '';
};

$emit('VARINT_UNSIGNED_INT', 'std::uint32_t', UNSIGNED_INT_CASES, static fn(int $v): string => Binary::writeUnsignedVarInt($v));
$emit('VARINT_SIGNED_INT', 'std::int32_t', SIGNED_INT_CASES, static fn(int $v): string => Binary::writeVarInt($v));
$emit('VARINT_UNSIGNED_LONG', 'std::uint64_t', UNSIGNED_LONG_CASES, static fn(int $v): string => Binary::writeUnsignedVarLong($v));
$emit('VARINT_SIGNED_LONG', 'std::int64_t', SIGNED_LONG_CASES, static fn(int $v): string => Binary::writeVarLong($v));

$emit('LE_UNSIGNED_SHORT', 'std::uint16_t', [0, 1, 255, 256, 65535], static fn(int $v): string => Binary::writeLShort($v));
$emit('LE_SIGNED_INT', 'std::int32_t', [0, -1, 2147483647, -2147483648, 123456], static fn(int $v): string => Binary::writeLInt($v));
$emit('LE_SIGNED_LONG', 'std::int64_t', [0, -1, 9223372036854775807, PHP_INT_MIN], static fn(int $v): string => Binary::writeLLong($v));

$dir = __DIR__ . '/../tests/fixtures';
@mkdir($dir, 0777, true);
file_put_contents($dir . '/encoding.inc', implode("\n", $lines) . "\n");

echo "Wrote tests/fixtures/encoding.inc\n";
