<?php
/*
 * Emits tests/Base64Fixtures.inc: every input paired with what PHP's base64_decode($s, true) does.
 *
 * The port's base64 decoder runs on the login JWT payload, not on the wire, so no packet suite can
 * reach it - a padding or truncation mistake there would go unnoticed until a real client failed to
 * log in. Rather than review it by eye, this asks PHP for the answer and the test demands the same
 * one, including on the malformed inputs where PHP returns false.
 *
 *   php tools/gen_base64_fixtures.php > tests/Base64Fixtures.inc
 */

declare(strict_types=1);

// Chosen to cover every branch: alphabet characters, both non-alphanumeric alphabet members,
// padding, whitespace (which PHP skips) and a character outside the alphabet entirely.
const ALPHABET = ['A', 'B', 'z', '9', '+', '/', '=', ' ', '!'];

/** @return list<string> every string of the given length over ALPHABET */
function permutations(int $length): array {
    if ($length === 0) {
        return [''];
    }
    $result = [];
    foreach (permutations($length - 1) as $prefix) {
        foreach (ALPHABET as $c) {
            $result[] = $prefix . $c;
        }
    }
    return $result;
}

$inputs = [];
for ($length = 0; $length <= 4; $length++) {
    $inputs = array_merge($inputs, permutations($length));
}

// Longer, well-formed payloads of every length modulo 3, which is what decides the padding.
mt_srand(0x5DEECE66D & 0x7FFFFFFF);
for ($length = 1; $length <= 64; $length++) {
    $raw = '';
    for ($i = 0; $i < $length; $i++) {
        $raw .= chr(mt_rand(0, 255));
    }
    $inputs[] = base64_encode($raw);
    $inputs[] = rtrim(base64_encode($raw), '=');  // unpadded, which PHP's strict mode accepts
}

function cppString(string $s): string {
    $out = '';
    foreach (str_split($s) as $c) {
        $out .= sprintf('\x%02x', ord($c));
    }
    return '"' . $out . '"';
}

echo "// Generated by tools/gen_base64_fixtures.php - do not edit.\n";
echo "// Each row is the input and its length, whether PHP's base64_decode(\$s, true) accepted it,\n";
echo "// and the decoded result and its length.\n";
foreach ($inputs as $input) {
    $decoded = base64_decode($input, true);
    $ok = $decoded !== false;
    $out = $ok ? $decoded : '';
    // The lengths are emitted because decoded data contains NUL bytes, and a string_view built from
    // a literal alone would stop at the first one.
    printf(
        "BP_BASE64_CASE(%s, %d, %s, %s, %d)\n",
        cppString($input),
        strlen($input),
        $ok ? 'true' : 'false',
        cppString($out),
        strlen($out)
    );
}
