/*
 * This file is part of BedrockProtocol for Endstone.
 * C++ port of the PHP original: src/types/command/CommandParameterTypes.php
 * Copyright (C) 2014-2022 PocketMine Team <https://github.com/pmmp/BedrockProtocol>
 *
 * BedrockProtocol is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

#pragma once

#include <cstdint>

namespace bedrock_protocol::types::command {

/**
 * This file is automatically generated; do NOT edit it by hand.
 * Regenerate it by running tools/generate-command-parameter-types.php
 */
class CommandParameterTypes final {
public:
    CommandParameterTypes() = delete; //NOOP

    static constexpr std::uint32_t INT = 1;                    // int
    static constexpr std::uint32_t VAL = 3;                    // float
    static constexpr std::uint32_t RVAL = 4;                   // value
    static constexpr std::uint32_t WILDCARDINT = 5;            // wildcard int
    static constexpr std::uint32_t OPERATOR = 6;               // operator
    static constexpr std::uint32_t COMPAREOPERATOR = 7;        // compare operator
    static constexpr std::uint32_t SELECTION = 8;              // target
    static constexpr std::uint32_t WILDCARDSELECTION = 10;     // target
    static constexpr std::uint32_t PATHCOMMAND = 17;           // filepath
    static constexpr std::uint32_t FULLINTEGERRANGE = 23;      // integer range
    static constexpr std::uint32_t EQUIPMENTSLOTENUM = 47;     // equipment slots
    static constexpr std::uint32_t ID = 56;                    // string
    static constexpr std::uint32_t POSITION = 64;              // x y z
    static constexpr std::uint32_t POSITION_FLOAT = 65;        // x y z
    static constexpr std::uint32_t MESSAGE_ROOT = 68;          // message
    static constexpr std::uint32_t RAWTEXT = 70;               // text
    static constexpr std::uint32_t JSON_OBJECT = 74;           // json
    static constexpr std::uint32_t BLOCK_STATE_ARRAY = 84;     // block states
    static constexpr std::uint32_t CLOCK_TIMEMARKER_NAME = 86; // timemarker name
    static constexpr std::uint32_t CODEBUILDERARGS = 88;       // command
};

}  // namespace bedrock_protocol::types::command
